export const actionTypes = {
    "CHANGE_PAGE": "CHANGE_PAGE",
    "CHANGE_USER": "CHANGE_USER",
    "CLOSE_MODAL": "CLOSE_MODAL",
    "CHANGE_MODAL": "CHANGE_MODAL",
    "STOP_SPINNER": "STOP_SPINNER",
    "SHOW_SPINNER": "SHOW_SPINNER",
    "FLUSH_MODAL": "FLUSH_MODAL"
}
